"""Initial migration2

Revision ID: 700be60f0c18
Revises: 
Create Date: 2024-07-09 20:29:37.225598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700be60f0c18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('post',
    sa.Column('Post_ID', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('Post_Text', sa.Text(length=1000000), nullable=False),
    sa.Column('User_Email', sa.String(length=320), nullable=False),
    sa.Column('Creation_DateTime', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['User_Email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('Post_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
